### ISSUE TITLE
PhD etc

### ISSUE THREAD

**Issue by ubcent** [azproduction/relocating-to-berlin#17]
Hello. I have some questions. Does Ph.D. is plus for German employers? What can you tell about other cities besides Berlin? Is there a problems with a driver's license? Now a lot of news about migrants in EU. Do you have any problems with that? Thanks.

**Comment by azproduction** [comment]
> Does Ph.D. is plus for German employers?

I general, startups do not care. For big companies it will be a plus for sure.

> What can you tell about other cities besides Berlin?

They are all more expensive then Berlin :)

> Is there a problems with a driver's license?

As a resident you can not drive a car using foreign drive licence after 6 months or so. You have to pass exams, all of them are possible in english. As a not a driver I can not suggest you much here.

> Now a lot of news about migrants in EU. Do you have any problems with that?

In short – No. Berlin is a city of expats, I constantly hear some English or even Russian on the streets. As a skilled and highly paid worker you will be welcomed, as it will be an instant benefit for a country.

**Comment by ubcent** [comment]
Thanks for answers :) Which technologies/frameworks are the most popular in Germany?

**Comment by azproduction** [comment]
> Which technologies/frameworks are the most popular in Germany?

I think as everywhere, just check general statistics.

**Comment by ubcent** [comment]
Thanks.

**Comment by lorey** [comment]
If you're interested or someone else is: In an old project of mine I have analyzed two German cities and other cities worldwide with respect to programming languages.

Here are the rankings (percentage means more/less popular in comparison to worldwide usage):

[**Berlin**](http://programmermap.com/area/berlin-germany/)
- Ruby +148%
- Shell +18%
- PHP +6%
- JavaScript +2%
- Python -9%
- CSS -30%
- C -33%
- Objective-C -45%
- Java -52%
- C++ -63%

[**Karlsruhe**](http://programmermap.com/area/karlsruhe-germany/)
- Shell +64%
- PHP +54%
- C++ +51%
- Java +37%
- Ruby +36%
- C +29%
- Python -5%
- CSS -32%
- JavaScript -37%
- Objective-C -76%

Source: [List of all cities](http://programmermap.com/area/)
