### ISSUE TITLE
Getting Blue Card for a spouse

### ISSUE THREAD

**Issue by khamukhin** [azproduction/relocating-to-berlin#23]
Hi guys!

Do you have any experience of getting Blue Card for a spouse? My spouse came to Germany with me holding a family reunification visa. Now my spouse got a job at a German IT-company. Is it worth/possible to try to get Blue Card instead of family reunification visa?

**Comment by azproduction** [comment]
With reunification visa she can work without any limitations on minimal salary. If she passes minimum salary requirements and her university has H+ then there will be no problem to make it, but I do not see a reason to have 2nd BC.

**Comment by azproduction** [comment]
@khamukhin I found one benefit. She will be able to get a unlimited residence permit after 21 or 33 months instead of 5 years. Without it she will get only visa.
